import 'entities.dart';

class FeriadosInit {
  static List<Feriado> get() => [
    Feriado(id: null, data: DateTime(2021, 1, 1), descricao: "Confraternização Universal"),
    Feriado(id: null, data: DateTime(2021, 2, 15), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2021, 2, 16), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2021, 4, 2), descricao: "Paixão de Cristo"),
    Feriado(id: null, data: DateTime(2021, 4, 21), descricao: "Tiradentes"),
    Feriado(id: null, data: DateTime(2021, 4, 4), descricao: "Páscoa"),
    Feriado(id: null, data: DateTime(2021, 5, 1), descricao: "Dia do Trabalhador"),
    Feriado(id: null, data: DateTime(2021, 6, 3), descricao: "Corpo de Cristo"),
    Feriado(id: null, data: DateTime(2021, 9, 7), descricao: "Independência"),
    Feriado(id: null, data: DateTime(2021, 10, 12), descricao: "Nossa Senhora Aparecida"),
    Feriado(id: null, data: DateTime(2021, 11, 2), descricao: "Finados"),
    Feriado(id: null, data: DateTime(2021, 11, 15), descricao: "Proclamação da República"),
    Feriado(id: null, data: DateTime(2021, 12, 25), descricao: "Natal"),
    Feriado(id: null, data: DateTime(2022, 1, 1), descricao: "Confraternização Universal"),
    Feriado(id: null, data: DateTime(2022, 2, 28), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2022, 3, 1), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2022, 4, 15), descricao: "Paixão de Cristo"),
    Feriado(id: null, data: DateTime(2022, 4, 21), descricao: "Tiradentes"),
    Feriado(id: null, data: DateTime(2022, 4, 17), descricao: "Páscoa"),
    Feriado(id: null, data: DateTime(2022, 5, 1), descricao: "Dia do Trabalhador"),
    Feriado(id: null, data: DateTime(2022, 6, 16), descricao: "Corpo de Cristo"),
    Feriado(id: null, data: DateTime(2022, 9, 7), descricao: "Independência"),
    Feriado(id: null, data: DateTime(2022, 10, 12), descricao: "Nossa Senhora Aparecida"),
    Feriado(id: null, data: DateTime(2022, 11, 2), descricao: "Finados"),
    Feriado(id: null, data: DateTime(2022, 11, 15), descricao: "Proclamação da República"),
    Feriado(id: null, data: DateTime(2022, 12, 25), descricao: "Natal"),
    Feriado(id: null, data: DateTime(2023, 1, 1), descricao: "Confraternização Universal"),
    Feriado(id: null, data: DateTime(2023, 2, 20), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2023, 2, 21), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2023, 4, 7), descricao: "Paixão de Cristo"),
    Feriado(id: null, data: DateTime(2023, 4, 21), descricao: "Tiradentes"),
    Feriado(id: null, data: DateTime(2023, 4, 9), descricao: "Páscoa"),
    Feriado(id: null, data: DateTime(2023, 5, 1), descricao: "Dia do Trabalhador"),
    Feriado(id: null, data: DateTime(2023, 6, 8), descricao: "Corpo de Cristo"),
    Feriado(id: null, data: DateTime(2023, 9, 7), descricao: "Independência"),
    Feriado(id: null, data: DateTime(2023, 10, 12), descricao: "Nossa Senhora Aparecida"),
    Feriado(id: null, data: DateTime(2023, 11, 2), descricao: "Finados"),
    Feriado(id: null, data: DateTime(2023, 11, 15), descricao: "Proclamação da República"),
    Feriado(id: null, data: DateTime(2023, 12, 25), descricao: "Natal"),
    Feriado(id: null, data: DateTime(2024, 1, 1), descricao: "Confraternização Universal"),
    Feriado(id: null, data: DateTime(2024, 2, 12), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2024, 2, 13), descricao: "Carnaval"),
    Feriado(id: null, data: DateTime(2024, 3, 29), descricao: "Paixão de Cristo"),
    Feriado(id: null, data: DateTime(2024, 4, 21), descricao: "Tiradentes"),
    Feriado(id: null, data: DateTime(2024, 3, 31), descricao: "Páscoa"),
    Feriado(id: null, data: DateTime(2024, 5, 1), descricao: "Dia do Trabalhador"),
    Feriado(id: null, data: DateTime(2024, 5, 30), descricao: "Corpo de Cristo"),
    Feriado(id: null, data: DateTime(2024, 9, 7), descricao: "Independência"),
    Feriado(id: null, data: DateTime(2024, 10, 12), descricao: "Nossa Senhora Aparecida"),
    Feriado(id: null, data: DateTime(2024, 11, 2), descricao: "Finados"),
    Feriado(id: null, data: DateTime(2024, 11, 15), descricao: "Proclamação da República"),
    Feriado(id: null, data: DateTime(2024, 12, 25), descricao: "Natal"),
  ];
}